// Code generated by go2go; DO NOT EDIT.


//line errors_test.go2:5
package errors

//line errors_test.go2:5
import "testing"

//line errors_test.go2:11
type e struct{}

func (a e) Error() string { return "error" }

func TestTryCatch(t *testing.T) {
//line errors_test.go2:15
 instantiate୦୦Try୦int(func() (int, error) {
//line errors_test.go2:17
  return 0, nil
	}).Catch(func(_ int, err error) int {
		t.Fatalf("catch error: %v", err)
		return 0
	}).Final(func(result int) {
		t.Log("errors: everything is good")
	})
//line errors_test.go2:23
 instantiate୦୦Try୦int(func() (int, error) {
//line errors_test.go2:26
  return 1, e{}
	}).Catch(func(result int, err error) int {
		t.Logf("captured result: %v", result)
		t.Logf("captured error: %v", err)
		return 1
	}).Final(func(result int) {
		if result != 1 {
			t.Fatalf("cannot capture error")
		}
	})
//line errors_test.go2:35
 instantiate୦୦Try୦int(func() (int, error) {
//line errors_test.go2:38
  return 1, nil
	}).Final(func(r int) {
		if r != 1 {
			t.Fatalf("result from try block is not as expected")
		}
	})
}
//line errors.go2:9
func instantiate୦୦Try୦int(e func() (int, error)) instantiate୦୦catch୦int {
	v, err := e()
	return instantiate୦୦catch୦int{err: err, result: v}
}

//line errors.go2:12
type instantiate୦୦catch୦int struct {
//line errors.go2:15
 err error
	result int
}

//line errors.go2:20
func (c instantiate୦୦catch୦int,) Catch(handler func(int, error) int,) instantiate୦୦catch୦int {
	if c.err != nil {
		c.result = handler(c.result, c.err)
	}
	c.err = nil
	return c
}

//line errors.go2:29
func (c instantiate୦୦catch୦int,) Final(handler func(int,)) {
	handler(c.result)
}

//line errors.go2:31
var _ = testing.AllocsPerRun
